name        : fixesproto
version     : 5.0
release     : 4
source      :
    - http://xorg.freedesktop.org/releases/individual/proto/fixesproto-5.0.tar.gz : 67865a0e3cdc7dec1fd676f0927f7011ad4036c18eb320a2b41dbd56282f33b8
license     :
    - MIT
summary     : X Fixes Extension
component   : xorg.proto
builddeps   :
    - pkgconfig(xextproto)
patterns    : /
description : |
    The extension makes changes to many areas of the protocol to resolve issues raised by application interaction with core protocol mechanisms that cannot be adequately worked around on the client side of the wire.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
